#!/bin/sh

rm -f test.db
sqlite3 test.db < $top_srcdir/mk-dnsdb.sql
$top_srcdir/import-zone.pl test.db $srcdir/example.com.zone

if [ ! -f test.db ]
then
	echo "test database not found."
	exit 1
fi

exit 0
